# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('org.apache.derby', 'derby', '10.15.2.1')
require_jar('org.apache.derby', 'derbyclient', '10.15.2.1')
require_jar('org.apache.derby', 'derbytools', '10.15.2.1')
require_jar('org.apache.derby', 'derbyshared', '10.15.2.1')
